swagger: "2.0"
info:
  title: "CircleCI API"
  version: "1.1"
host: "circleci.com"
basePath: "/api/v1.1"
schemes:
- "https"
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /projects:
    get:
      summary: "List of all the projects you're following on CircleCI, with build information organized by branch."
      operationId: "getProjects"
      responses:
        200:
          schema:
            type: array
            items:
              $ref: "#/definitions/Project"
definitions:
  Project:
    properties:
      username:
        type: string
    additionalProperties: false
